import FullScreenLoader from "@/common/FullScreenLoader";
import { fetchTermsConditions } from "@/lib/api";
import { useQuery } from "@tanstack/react-query";
import React from "react";

const TermsAndConditions: React.FC = () => {

  const { data, isLoading, isSuccess } = useQuery({
    queryKey: [ 'fetchTermsConditions' ],
    queryFn: fetchTermsConditions,
    retry: 2,
    select: (data) => data.data[0]
  });

  let content;

  if(isLoading){
    content = <FullScreenLoader/>
  }

  if(isSuccess){
    content = (
      <main className="container mx-auto px-4 py-10 max-w-4xl text-neutral-800 leading-7">
        <h1 className="text-3xl font-bold mb-6">{data.page_title}</h1>

        <div dangerouslySetInnerHTML={{ __html: data.page_content }} className="space-y-4"></div>

        {/* <p className="mb-4">
          This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
        </p>

        <p className="mb-4">
          This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name Naturalla.store (“Website”), including the related mobile site and mobile application (hereinafter referred to as “Platform”).
        </p>

        <p className="mb-4">
          The Platform is owned by NATURALLA LILYFE PRIVATE LIMITED, a company incorporated under the Companies Act, 1956 with its registered office at DOOR NO. 29 B3, GROUND FLOOR, SRK COMPLEX, GANDHI STREET, KUMARAN NAGAR, Vilankurichi, Coimbatore - 641035, Tamil Nadu (hereinafter referred to as "Platform Owner", "we", "us", "our").
        </p>

        <p className="mb-4">
          Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference.
        </p>

        <ul className="list-disc list-inside mb-4 space-y-2">
          <li>If you transact on the Platform, you shall be subject to the policies applicable to such transactions.</li>
          <li>By mere use of the Platform, you contract with the Platform Owner and agree to these terms and policies.</li>
          <li>These Terms relate to your use of our website, goods, or services (collectively “Services”).</li>
          <li>Any terms proposed by you that conflict with these Terms are rejected and void.</li>
          <li>These Terms may be modified at any time without notice.</li>
          <li>You must periodically review the Terms to stay updated.</li>
        </ul>

        <p className="mb-4">
          For the purpose of these Terms, "you", “your” or "user" shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
        </p>

        <p className="mb-4 font-semibold uppercase">
          Accessing, browsing or otherwise using the Platform indicates your agreement to all the terms and conditions under these Terms of Use. Please read carefully before proceeding.
        </p>

        <p className="mb-4">The use of the Platform and/or Services is subject to the following Terms of Use:</p>

        <ul className="list-disc list-inside mb-4 space-y-2">
          <li>To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.</li>
          <li>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</li>
          <li>Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.</li>
          <li>The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.</li>
          <li>You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.</li>
          <li>You agree to pay us the charges associated with availing the Services.</li>
          <li>You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.</li>
          <li>You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information.</li>
          <li>You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.</li>
          <li>You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys’ fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.</li>
          <li>In no event will the Platform Owner be liable for any indirect, consequential, incidental, special or punitive damages, including without limitation damages for loss of profits or revenues, business interruption, loss of business opportunities, loss of data or loss of other economic interests, whether in contract, negligence, tort or otherwise, arising from the use of or inability to use the Services, however caused and whether arising in contract, tort, negligence, warranty or otherwise, exceed the amount paid by You for using the Services giving rise to the cause of action or Rupees One Hundred (Rs. 100) whichever is less</li>
          <li>Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.</li>
          <li>These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.</li>
          <li>All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in COIMBATORE, TAMILNADU.</li>
          <li>All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.</li>
        </ul> */}
      </main>
    )
  }

  

  return content;
};

export default TermsAndConditions;
