import React from "react";

const TermsAndConditions: React.FC = () => {
  return (
    <main className="container mx-auto px-4 py-10 max-w-4xl text-neutral-800 leading-7">
      <h1 className="text-3xl font-bold mb-6">Terms &amp; Conditions</h1>

      <p className="mb-4">
        This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
      </p>

      <p className="mb-4">
        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name Naturalla.store (“Website”), including the related mobile site and mobile application (hereinafter referred to as “Platform”).
      </p>

      <p className="mb-4">
        The Platform is owned by NATURALLA LILYFE PRIVATE LIMITED, a company incorporated under the Companies Act, 1956 with its registered office at DOOR NO. 29 B3, GROUND FLOOR, SRK COMPLEX, GANDHI STREET, KUMARAN NAGAR, Vilankurichi, Coimbatore - 641035, Tamil Nadu (hereinafter referred to as "Platform Owner", "we", "us", "our").
      </p>

      <p className="mb-4">
        Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference.
      </p>

      <ul className="list-disc list-inside mb-4 space-y-2">
        <li>If you transact on the Platform, you shall be subject to the policies applicable to such transactions.</li>
        <li>By mere use of the Platform, you contract with the Platform Owner and agree to these terms and policies.</li>
        <li>These Terms relate to your use of our website, goods, or services (collectively “Services”).</li>
        <li>Any terms proposed by you that conflict with these Terms are rejected and void.</li>
        <li>These Terms may be modified at any time without notice.</li>
        <li>You must periodically review the Terms to stay updated.</li>
      </ul>

      <p className="mb-4">
        For the purpose of these Terms, "you", “your” or "user" shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
      </p>

      <p className="mb-4 font-semibold uppercase">
        Accessing, browsing or otherwise using the Platform indicates your agreement to all the terms and conditions under these Terms of Use. Please read carefully before proceeding.
      </p>

      <p className="mb-4">The use of the Platform and/or Services is subject to the following Terms of Use:</p>

      <ul className="list-disc list-inside mb-4 space-y-2">
        <li>You agree to provide true, accurate and complete information during and after registration.</li>
        <li>You are responsible for all acts done using your registered account.</li>
        <li>We do not guarantee the accuracy, performance, or suitability of any information on the Platform.</li>
        <li>You use our Services and Platform at your own risk and discretion.</li>
        <li>The content of the Platform is proprietary and licensed to us — you cannot claim IP rights on it.</li>
        <li>Unauthorized use may result in legal action under these Terms or applicable laws.</li>
        <li>You agree to pay the charges associated with availing our Services.</li>
        <li>You agree not to use the Platform/Services for illegal or prohibited purposes.</li>
        <li>Links to third-party sites are governed by their own terms and policies.</li>
        <li>By transacting, you are entering a legally binding contract with the Platform Owner.</li>
        <li>You shall indemnify and hold harmless Platform Owner, affiliates, and employees from any third-party claims, penalties, or legal issues arising from your breach of these Terms.</li>
      </ul>

      <p className="mb-4">
        In no event will the Platform Owner be liable for:
      </p>
      <ul className="list-disc list-inside mb-4 space-y-2">
        <li>Any indirect, consequential, incidental, special, or punitive damages</li>
        <li>Loss of profits, business, data, or other economic interests</li>
        <li>Amount exceeding what you paid for the Services or INR 100, whichever is lower</li>
      </ul>

      <ul className="list-disc list-inside mb-4 space-y-2">
        <li>Force majeure events can exempt parties from liability for delays or non-performance.</li>
        <li>These Terms are governed by the laws of India.</li>
        <li>All disputes shall be subject to the exclusive jurisdiction of the courts in Coimbatore, Tamil Nadu.</li>
        <li>For any concerns, contact us via the information provided on the website.</li>
      </ul>
    </main>
  );
};

export default TermsAndConditions;
